### ISSUE TITLE
Фикс уязвимости

### ISSUE THREAD

**Issue by chmaxx** [chmaxx/staysecured#22]
Tracking issue for:
- [ ] https://github.com/chmaxx/staysecured/security/code-scanning/1

**Comment by whitekeep** [comment]
Значит просто жмём эту волшебную кнопочку. 
![image](https://user-images.githubusercontent.com/60810530/142756985-2cd492b1-8422-4c47-8ea5-e3742eff68cc.png)

**Comment by whitekeep** [comment]
Я глянул на его претензию, он похоже думает что мы хранив в куках пароль в открытом виде

**Comment by chmaxx** [comment]
да, закрываем
